name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 3: Upload SSH private key for EC2
      - name: Upload SSH private key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Step 4: Deploy to EC2 via SSH
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Navigate to your project folder
            cd ~/media-sharing-platform

            # Pull the latest changes from GitHub
            git pull origin main

            # Install any new dependencies
            npm install

            # Restart the application (you can use pm2 or systemd, for example)
            pm2 restart media-server || pm2 start npm --name "your-app-name" -- start

          EOF

      # Step 5: Clean up (optional)
      - name: Clean up
        run: |
          echo "Deployment completed."
