name: Deploy to GCP VM on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Start SSH Agent and Add Private Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_PRIVATE_KEY }}
      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.GCP_PUBLIC_IP }} >> ~/.ssh/known_hosts
      - name: SSH into GCP and Pull Latest
        run: |
          ssh ${{ secrets.GCP_USER }}@${{ secrets.GCP_PUBLIC_IP }} << 'EOF'
            cd ~/media-app/backend
            git pull origin main
          EOF